### PR TITLE
Update python docs

### LINKED ISSUE #20: Display on 18F pages is not quite right
There are some sections and some subsections in the Python portion, at least, that may not be displaying at all. There is also some stray boilerplate that should be removed. See:

https://pages.18f.gov/testing-cookbook/python/

But the doctest sub-pages are not showing up.

https://github.com/18F/testing-cookbook/tree/18f-pages/pages/python/doctest

There are some broken links, as well.

### PR DESCRIPTION
**Pull request by jmcarp**
Warning: this is an opinionated patch! I deemphasized doctest (which isn't a testing framework and shouldn't be treated as such) and moved pytest to the top. I also deleted most of the code examples, since they were hard to find--and, more importantly, because many excellent examples already exist, often on the first page of the official docs.
- Add testing libraries
- Add testing resources
- Remove standalone code examples, since they're hard to find; prefer
  linking to existing examples, of which there are many

[Resolves #20]

cc @mbland @arowla

### CODE REVIEW

**Comment by arowla** [comment]
I don't object to jettisoning the examples or the reordering, but I do object to removing my `nose` tips. :stuck_out_tongue: Unless they can be reworked to apply to pytest.... But I have barely ever used pytest, so I wouldn't know.

**Comment by jmcarp** [comment]
@arowla: what do you think about moving the nose tips to a separate file? I was also trying to get the main python page to fit inside a screen or two. If linking to third-party guides won't cut it, I think it would make sense to add nested pages for examples on specific test runners.

**Comment by arowla** [comment]
:+1:

On Fri, Nov 20, 2015 at 11:28 AM, Joshua Carp notifications@github.com
wrote:

> @arowla https://github.com/arowla: what do you think about moving the
> nose tips to a separate file? I was also trying to get the main python page
> to fit inside a screen or two. If linking to third-party guides won't cut
> it, I think it would make sense to add nested pages for examples on
> specific test runners.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/18F/testing-cookbook/pull/23#issuecomment-158451233.

## 

Alison Rowland
Technical Lead, https://fbopen.gsa.gov | 18F
202-317-0124

**Comment by jmcarp** [comment]
Updated. Not sure why travis is failing, or even enabled.

**Comment by mbland** [comment]
Oh, I enabled a bunch of repos before adding `.travis.yml` files. My bad. I'll start adding them.

**Comment by arowla** [comment]
Since Travis is just failing on a technicality, going to merge.

**Pull request merged**
