### PR TITLE
Use guides_style_18f gem

### PR DESCRIPTION
**Pull request by mbland**
cc: @arowla @monfresh @jmcarp @shawnbot

### CODE REVIEW

**Comment by monfresh** [comment]
I think I understand what this does, but I think it would be helpful to have a record of why this change is needed. On the save-ferris team, we've started using this format for commit messages:

```
Some awesome title

Why:

* ...

How:

* ...
```

**Comment by mbland** [comment]
Why:
- Makes it easier to roll out style and structure updates across the set of 18F Guides (and other docs using the same template).

How:
- Integrates the `guides_style_18f` gem, which contains the standard HTML, CSS, and JS fragments/assets common to the style.
- Most style updates to docs using this gem will roll out automatically, thanks to the `asset_root:` attribute pointing to https://pages.18f.gov/guides-template/.
- Other style updates can be updated via `bundle update guides_style_18f`, which we also hope to automate with webhooks.
- Individual style elements can be overridden (though this needs to be better documented).
- More info: https://github.com/18F/guides-style/

**Comment by arowla** [comment]
I included the why and how in the merge commit: https://github.com/18F/testing-cookbook/commit/e2f1a9d741da4eb1e290d1a5448e8940d9573958

**Comment by monfresh** [comment]
Thanks, @arowla! That's a great looking commit message, @mbland.

**Pull request merged**
