### PR TITLE
Add pytest intro and examples

### PR DESCRIPTION
**Pull request by jmcarp**
Pytest is neat.

### CODE REVIEW

**Comment by mbland** [comment]
Can you update this to merge into `18F:gh-pages`?

**Comment by jmcarp** [comment]
Sure. Should examples be in separate files or inline? Some are basically pseudocode and wouldn't run as-is. Happy to flesh those out or pare down as necessary.

**Comment by arowla** [comment]
I think inline is good, but they should probably runnable.

On Tue, Apr 7, 2015 at 1:21 PM, Joshua Carp notifications@github.com
wrote:

> Sure. Should examples be in separate files or inline? Some are basically
> pseudocode and wouldn't run as-is. Happy to flesh those out or pare down as
> necessary.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/18F/testing-cookbook/pull/5#issuecomment-90653037.

## 

Alison Rowland
Technical Lead, https://fbopen.gsa.gov | 18F
202-317-0124

**Comment by jmcarp** [comment]
Got it. Closing in favor of #6.

**Pull request closed without merging**
